[workspace]
resolver = "2"
members = ["runtime", "cargo-xxfunc", "xxfunc"]

[workspace.package]
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
reth-exex = { git = "https://github.com/paradigmxyz/reth", features = [
    "serde",
], version = "1.0.2" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", version = "1.0.2" }
reth = { git = "https://github.com/paradigmxyz/reth", version = "1.0.2" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", version = "1.0.2" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", version = "1.0.2" }
reth-exex-types = { git = "https://github.com/paradigmxyz/reth", version = "1.0.2" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", version = "1.0.2" }


tokio = { version = "1.0", features = ["full"] }
eyre = "0.6"
jsonrpsee = { version = "0.23", features = ["server", "macros"] }
async-trait = "0.1"
wasi-common = "22"
wasmtime = "22"
serde_json = "1"
base64 = "0.22.1"
