[package]
name = "xxfunc-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.30"
hyper = { version = "1.4.1", features = ["full"] }
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }

# protobuf
tonic = "0.12.1"
prost = "0.13.1"

# wasm
wasi-common = "22"
wasmtime = "22"
eyre = "0.6.12"
tracing = "0.1.40"

[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }
